boosst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('register_user_email', views.register_username_email,
         name='register-user-email'),
    path('register_password', views.register_password, name='register-password'),
    path('trainer', views.trainer, name='trainers'),
    path('course', views.course, name='courses'),
    path('client', views.client, name='clients'),
    path('reporting', views.reporting, name='reporting'),
    path('employee', views.employee, name='employees'),
    path('employees/tracking', views.employees_tracking, name='employees-tracking'),
    path('employees/tracking/<int:id>', views.employees_tracking_detail,
         name='employees-tracking-detail'),
    path('employee_profile/', views.employee_profile, name='employee_profile'),
    path('employee_profile/my-tasks', views.my_tasks, name='my-tasks'),
    path('employee_profile/my-tasks/<int:id>',
         views.my_tasks_detail, name='my-tasks-detail'),
     # activity
    path('employee_profile/my-activity', views.my_activity, name='my-activity'),
    path('employee_profile/my-activity/add-activity', views.create_activity, name='add-activity'),
    path('employee_profile/my-activity/add-activity/<int:id>', views.update_activity, name='update-activity'),

    path('employee_profile/my-activity/<int:id>', views.delete_activity, name='delete-activity'),

    path('employee_profile/my-activity/detail/<int:id>', views.activity_detail, name='my-activity-detail'),
     
     #chatbot
      path('employee_profile/ai-assistant', views.ai_assistant, name='ai-assistant'),

     #  path('getResponse',views.getResponse,name='getResponse'),

     # logout

    path('logout',
         views.logout_user, name='logout'),


    # //////Reset Views
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_send.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
         name='password_reset_complete'),
]

pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
# Create your models here.
from django.db import models


class Department(models.Model):
    DepartmentID = models.AutoField(primary_key=True)
    DepartmentName = models.CharField(max_length=255)

    def __str__(self):
        return self.DepartmentName


class JobTitle(models.Model):
    JobTitleID = models.AutoField(primary_key=True)
    JobTitleName = models.CharField(max_length=255)
    Responsibilities = models.TextField()
    Qualifications = models.TextField()

    def __str__(self):
        return self.JobTitleName


class Employee(models.Model):
    EmployeeID = models.AutoField(primary_key=True)
    FirstName = models.CharField(max_length=255)
    LastName = models.CharField(max_length=255)
    Email = models.EmailField()
    Phone = models.CharField(max_length=20)
    Department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True)
    JobTitle = models.ForeignKey(
        JobTitle, on_delete=models.SET_NULL, null=True)
    HireDate = models.DateField(default=datetime.today())
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, default=None)
    EmployeePhoto = models.ImageField(
        upload_to='employee_photos/', default='employee_photos/default-employee.webp', null=True, blank=True)
    Location = models.CharField(max_length=50, null=True)
    PerHour = models.CharField(max_length=10, null=True)
    EmployeeTarget = models.IntegerField(max_length=10, null=True, blank=True)
    MinTarget = models.IntegerField(max_length=3, null=True, blank=True)

    def __str__(self):
        return self.FirstName


class Status(models.Model):
    StatusID = models.AutoField(primary_key=True)
    StatusName = models.CharField(max_length=255)
    StatusDescription = models.TextField()

    def __str__(self):
        return self.StatusName


class Task(models.Model):
    TaskID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    Status = models.ForeignKey(
        Status, on_delete=models.CASCADE, null=True, default=2)
    TaskName = models.CharField(max_length=255)
    Description = models.TextField(default="default description", null=True)
    Deadline = models.DateField(default=datetime.today(), null=True)
    TaskDuration = models.IntegerField(default=1, null=True)
    TaskPriority = models.CharField(max_length=10, default='normal', null=True)

    def __str__(self):
        return self.TaskName


class TaskProgress(models.Model):
    ProgressID = models.AutoField(primary_key=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE)
    Status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    StartDate = models.DateField()
    EndDate = models.DateField()
    Comments = models.TextField()

    def __str__(self):
        return str(self.Status)


class Performance(models.Model):
    PerformanceID = models.AutoField(primary_key=True)
    # OneToOneField instead of ForeignKey
    Employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
    TaskPoints = models.IntegerField()
    QualityPoints = models.IntegerField()
    HoursWorkedPoints = models.IntegerField()
    MeetingAttendancePoints = models.IntegerField()
    TotalPoints = models.IntegerField()
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    Badge = models.ForeignKey('Badge', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.Employee.FirstName} - TaskPoints: {self.TaskPoints}'


class Badge(models.Model):
    BadgeID = models.AutoField(primary_key=True)
    BadgeName = models.CharField(max_length=255)
    Description = models.TextField()
    BadgeImage = models.ImageField(
        upload_to='badge_images/', null=True, blank=True)

    def __str__(self):
        return self.BadgeName


class Salesman(models.Model):
    SalesmanID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    SalesTarget = models.DecimalField(max_digits=10, decimal_places=2)
    SalesAchievement = models.DecimalField(max_digits=10, decimal_places=2)
    SalesProgress = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'{self.Employee.FirstName} - Sales Target: {self.SalesTarget}'


class Trainer(models.Model):
    TrainerID = models.AutoField(primary_key=True)
    FirstName = models.CharField(max_length=255)
    LastName = models.CharField(max_length=255)
    Phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50 ,default="example@email.com")
    Qualifications = models.TextField(null=True,blank=True)
    Certificates = models.FileField(null=True,blank=True,upload_to='pdf')
    Certificate2 = models.FileField(null=True,blank=True,upload_to='pdf')
    Certificate3 = models.FileField(null=True,blank=True,upload_to='pdf')
    Location = models.TextField(default='EGY',max_length=20)
    Comments = models.TextField(null=True,blank=True)
    rates = models.IntegerField(default=50)

    def __str__(self):
        return self.FirstName


class Course(models.Model):
    CourseID = models.AutoField(primary_key=True)
    CourseName = models.CharField(max_length=255)
    # new data
    InstructorName = models.CharField(max_length=255, null=True)
    Location = models.CharField(max_length=50, null=True)
    Duration = models.CharField(max_length=50, null=True)
    Price = models.CharField(max_length=50, null=True)
    # new data
    Description = models.TextField()
    StartDate = models.DateField()
    EndDate = models.DateField()
    PublicCourse = models.BooleanField()
    CourseMaterialsURL = models.URLField()

    def __str__(self):
        return self.CourseName


class SalesmanCourseAssignment(models.Model):
    AssignmentID = models.AutoField(primary_key=True)
    Salesman = models.ForeignKey(Salesman, on_delete=models.CASCADE)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    AssignmentDate = models.DateField()

    def __str__(self):
        return f'Salesman: {self.Salesman.Employee.FirstName} - Course: {self.Course.CourseName} - AssignmentID: {self.AssignmentID}'


class TrainerCourseAssignment(models.Model):
    AssignmentID = models.AutoField(primary_key=True)
    Trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    AssignmentDate = models.DateField()

    def __str__(self):
        return f'Trainer: {self.Trainer.FirstName} - Course: {self.Course.CourseName} - AssignmentID: {self.AssignmentID}'


class EmployeeBadge(models.Model):
    EmployeeBadgeID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    Badge = models.ForeignKey(Badge, on_delete=models.SET_NULL, null=True)
    DateEarned = models.DateField()

    def __str__(self):
        return f'{self.Employee.FirstName} - Badge: {self.Badge.BadgeName} - BadgeID: {self.EmployeeBadgeID}'


class Meeting(models.Model):
    MeetingID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    MeetingDate = models.DateField()
    AttendanceStatus = models.BooleanField()
    MinutesDuration = models.IntegerField()

    def __str__(self):
        return f'{self.Employee.FirstName} - Attendance: {self.AttendanceStatus}'


class TaskQualityRating(models.Model):
    RatingID = models.AutoField(primary_key=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE)
    QualityRating = models.IntegerField()
    Reviewer = models.ForeignKey(
        Employee, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'Task: {self.Task.TaskName} - Quality Rating: {self.QualityRating}'
# ... (remaining code)


class EmployeeSkill(models.Model):
    SkillID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    SkillName = models.CharField(max_length=255)
    SkillLevel = models.IntegerField()

    def __str__(self):
        return f'{self.Employee.FirstName} - Skill: {self.SkillName} - Level: {self.SkillLevel}'


class TaskDeliverable(models.Model):
    DeliverableID = models.AutoField(primary_key=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE)
    DeliverableName = models.CharField(max_length=255)
    DeliverableDescription = models.TextField()
    DeliverableFile = models.FileField(
        upload_to='deliverables/', default='default_file.pdf')

    def __str__(self):
        return self.DeliverableName


class Client(models.Model):
    ClientID = models.AutoField(primary_key=True)
    FirstName = models.CharField(max_length=255)
    LastName = models.CharField(max_length=255)
    Phone = models.CharField(max_length=20)
    Company = models.CharField(max_length=20)
    Project = models.CharField(max_length=20)
    Location = models.CharField(max_length=20)

    def __str__(self):
        return self.FirstName
    
class Activity(models.Model):
    ActivityID = models.AutoField(primary_key=True)
    Employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    ActivityName = models.CharField(max_length=255)
    Description = models.TextField(default="default description", null=True)
    Project = models.CharField(max_length=20 ,null=True,blank=True)
    DoneDate = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.ActivityName

templates/pages/add-activity.html
{% extends 'base_custom.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'front-end-static/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'front-end-static/css/style.min.css' %}">
{% endblock style %}


{% block title %}
Employees|Page
{% endblock title %}



{% block content %}
{% include 'parts/navbar.html' %}
<div class="row m-0">
    {% include 'parts/side_nav.html' %}
    <div class="col-9 employees_content mt-4 offset_left" id="side_content">
        <h3 class="text-capitalize my-2">Add Activity</h3>
        <form action="" method="post" class="mt-3">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Activity Title</label>
                <input type="text" class="form-control" name="ActivityName" id="exampleFormControlInput1"
                    placeholder="Activity name">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control" name="Description" placeholder="Activity Description"
                    id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Related Project</label>
                <input type="text" class="form-control" name="Project" id="exampleFormControlInput1"
                    placeholder="the Related Project">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Date and Time</label>
                <input type="datetime-local" class="form-control" name="DoneDate" id="exampleFormControlInput1">
            </div>

            <button type="submit" class="btn btn-info text-white mt-3">
                <span>
                    Create
                </span>
            </button>
        </form>


    </div>
</div>


<!-- JAVASCRIPT LOGIC @@@@@@@ -->

{% endblock content %}

templates/pages/ai-assistant.html
{% extends 'base_custom.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'front-end-static/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'front-end-static/css/style.min.css' %}">
<style>
    #chatbot {
        margin-left: auto;
        margin-right: auto;
        width: 70%;
        margin-top: 50px;
        border-radius: 10px;
        border: 1px solid gray;
        padding: 10px;
        height: 300px;
        overflow: auto;
    }

    .botText {
        font-family: monospace;
        font-size: 18px;
        text-align: left;
        line-height: 25px;
        color: rgb(109, 111, 109);
    }

    #userInput {
        margin-left: auto;
        margin-right: auto;
        width: 70%;
        margin-top: 40px;
        text-align: center;
    }

    #textInput {
        border: 3px solid white;
        border-bottom: 3px solid #00314B;
        font-family: monospace;
        font-size: 18px;
        width: 60%;
        padding: 16px;
        color: #FFA600;
    }

    #textInput:focus {
        outline: none;
    }

    .userText {
        text-align: right;
        font-family: monospace;
        font-size: 18px;
        line-height: 25px;
        color: rgb(109, 111, 109);
    }
</style>
{% endblock style %}


{% block title %}
AI Assistant | Page
{% endblock title %}



{% block content %}
{% include 'parts/navbar.html' %}
<div class="row m-0">
    {% include 'parts/side_nav.html' %}
    <div class="col-9 employees_content mt-4 offset_left" id="side_content">
        <h3 class="text-capitalize my-2">Boost Community Chatbot</h3>
        <div>
            <div id="chatbot">
                <p class="botText">Hi ,My name is BoostCommunity and iam your virtual assistant. </p>
            </div>
            <div id="userInput">
                <input type="text" id="textInput" name="userMessage" placeholder="Type your message...">

                <button type="submit" id="buttonInput" class="btn btn-info text-white mt-3">
                    <span>
                        Send
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>


<!-- JAVASCRIPT LOGIC @@@@@@@ -->
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>

<script>

    console.log('/{% url "getResponse" %}');

    function getUserResponse()
    {
        var userText = $('#textInput').val();
        var userHTML = `<p class='userText'>{{employee.FirstName}}: <span>${userText}</span></p>`;
        $("#textInput").val("");
        $('#chatbot').append(userHTML);

        $.get('{% url "getResponse" %}', { userMessage: userText }).done((data) =>
        {
            var returnedMessage = `<p class='botText'>BoostCommunity: <span>
                ${data}</span></p>`
            $('#chatbot').append(returnedMessage)
        })
    };


    $('#buttonInput').click(() =>
    {
        getUserResponse();
    })
</script>
{% endblock content %}

templates/pages/my_task_detail.html
{% extends 'base_custom.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'front-end-static/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'front-end-static/css/style.min.css' %}">
{% endblock style %}


{% block title %}
Courses|Page
{% endblock title %}


{% block content %}



{% include 'parts/navbar.html' %}
<div class="row ">
    {% include 'parts/side_nav.html' %}
    <div class="mt-3" style="max-height: 200px;">
        <div class="mx-3 p-3">
            <p>{% now "jS F Y" %}</p>
            <h2 class="my-4">Good evening , {{ employee.FirstName|title }} {{ employee.LastName|title}}</h2>
            <h4 class="fw-normal">Your Task: </h4>
        </div>
        <div class="position-relative">
            <div class=" position-absolute top-50 start-50 border p-3 rounded" style="transform: translate(-50%,11%);">
                <h3>
                    Task Name:
                    <small class="text-body-secondary">{{selected_task.TaskName}}
                        ({{selected_task.Status.StatusName}})</small>
                </h3>
                <h5 class="mt-3">
                    Description:
                    <small class="text-body-secondary">{{selected_task.Description}}</small>
                </h5>
                <h5 class="mt-3">
                    Deadline:
                    <small class="text-body-secondary">{{selected_task.Deadline}}</small>
                </h5>
                <h5 class="mt-3">
                    Priority:
                    <small class="text-body-secondary">{{selected_task.TaskPriority}}</small>
                </h5>
            </div>
        </div>
    </div>


</div>
</div>



{% endblock content %}

templates/pages/task_tracking_detail.html
{% extends 'base_custom.html' %}
{% load static %}


{% block style %}

<link rel="stylesheet" href="{% static 'front-end-static/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'front-end-static/css/style.min.css' %}">

{% endblock style %}

{% block title %}
Tracking Employees
{% endblock title %}



{% block content %}




{% include 'parts/navbar.html' %}
<div class="row m-0">
    {% include 'parts/side_nav.html' %}
    <div class="col-9 tracking_content mt-4 offset_left" id="side_content">
        <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#" class="link-underline link-underline-opacity-0">Employees</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Tracking mode</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-4">
                <div class="persons rounded-2" style="padding: 24px;">
                    <div>
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="search_container">
                                <form>
                                    <input type="text" name="qe" class="form-control" placeholder="Search...">
                                </form>
                            </div>
                            <button type="button" class="btn ">
                                <img src="{% static 'front-end-static/images/icons/table/sort.svg' %}" class="icon"
                                    alt="icon">
                            </button>
                            <button type="button" class="btn ">
                                <img src="{% static 'front-end-static/images/icons/table/filter.svg' %}" class="icon"
                                    alt="icon">
                            </button>
                        </div>
                    </div>
                    <ul class="list-group">

                        {% for emp in employees %}
                        <li class="list-group-item 
                            
                            {% if id == selected_employee.pk%}
                                
                            {% else %}
                            {% endif %}
                               employeesList ">
                            <!-- you can add class selected or not selected -->
                            <a href="{% url 'employees-tracking' %}/{{emp.EmployeeID}} " style="text-decoration: none;">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <div>
                                        <img src="{{emp.EmployeePhoto.url}}" class="emp_image" alt="employee">
                                        <span class="fw-bold">{{emp.FirstName|title}} {{emp.LastName|title}}</span>
                                    </div>
                                    <div class="btn-group me-2" role="group" aria-label="First group">
                                        <button type="button" class="btn fw-bold total btn-outline-secondary">
                                            {{emp.task_set.count}}
                                        </button>
                                        <button type="button"
                                            class="btn fw-bold in_progress btn-outline-secondary">0</button>
                                        <button type="button"
                                            class="btn fw-bold overdue btn-outline-secondary">0</button>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="job_container rounded-pill d-flex align-items-center">
                                        <img src="{% static 'front-end-static/images/icons/job.svg' %}" alt="Job icon">
                                        <span>{{emp.JobTitle|upper}}</span>
                                    </div>
                                    <div class="location_container rounded-pill d-flex align-items-center">
                                        <img src="{% static 'front-end-static/images/icons/location.svg' %}"
                                            alt="location icon">
                                        <span>{{emp.Location|upper}}</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        {% endfor %}


                    </ul>
                </div>
            </div>
            <div class="col-8">
                <!-- DATA@@@@@@@@@@@@@@@@@@ -->
                <div class="data rounded-2" style="min-height: 544.5px;">
                    <div class="data_head d-flex align-items-center">
                        <div class="employee d-inline-flex align-items-center me-2 flex-grow-1">
                            <img src="{{selected_employee.EmployeePhoto.url}}" class="emp_image" alt="employee">
                            <h6 class="fw-bold ms-1">{{selected_employee.FirstName}}</h6>
                        </div>
                        <div class="task_card justify-content-around d-inline-flex align-items-center rounded-2">
                            <span>Total tasks</span>
                            <h5>{{selected_employee.task_set.all.count}}</h5>
                            <img src="{% static 'front-end-static/images/icons/total.svg' %}" alt="icon">
                        </div>
                        <div class="task_card justify-content-around d-inline-flex align-items-center rounded-2">
                            <span>In progress</span>
                            <h5>{{inprogress_tasks.count}}</h5>
                            <img src="{% static 'front-end-static/images/icons/in_progress.svg' %}" alt="icon">
                        </div>
                        <div class="task_card justify-content-around d-inline-flex align-items-center rounded-2">
                            <span>Overdue</span>
                            <h5>{{overdue_tasks.count}}</h5>
                            <img src="{% static 'front-end-static/images/icons/overdue.svg' %}" alt="icon">
                        </div>
                    </div>
                    <div class="d-flex align-items-center justify-content-between mt-3">
                        <div class="search_container">
                            <input type="text" class="form-control" placeholder="Search...">
                        </div>
                        <div>
                            <button type="button" class="btn ">
                                <img src="{% static 'front-end-static/images/icons/table/sort.svg' %}" class="icon"
                                    alt="icon">
                            </button>
                            <button type="button" class="btn ">
                                <img src="{% static 'front-end-static/images/icons/table/filter.svg' %}" class="icon"
                                    alt="icon">
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="tasks_data" style="max-height: 50vh; overflow: auto;">
                        <!-- Tasks LOOP @@@@@@@@@@@ -->

                        {% if selected_employee.task_set.all %}
                        {% for task in selected_employee.task_set.all %}

                        <table class="table table-borderless">
                            <thead>
                                <tr>
                                    <th scope="col">Task name</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Deadline</th>
                                    <th scope="col">Project</th>
                                    <th scope="col">Customer</th>
                                    <th scope="col">Assigned by</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">{{task.TaskName|truncatechars:9}} </th>
                                    <td>{{task.Status}}</td>
                                    <td>{{task.Deadline}}</td>
                                    <td>Boost Community</td>
                                    <td>Rania</td>
                                    <td>CEO</td>
                                </tr>
                            </tbody>
                        </table>
                        {% endfor %}
                        {% else %}
                        <h3>No Tasks for {{selected_employee}}</h3>
                        {% endif %}



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    const employeesList = document.querySelectorAll(".employeesList");
    console.log(employeesList);
    employeesList.forEach((item) =>
    {
        item.addEventListener('mouseover', () =>
        {
            item.style.background = '#e6eef2'
        })
        item.addEventListener('mouseout', () =>
        {
            item.style.background = ''
        })

    });
</script>
{% endblock content %}

templates/pages/update-activity.html
{% extends 'base_custom.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'front-end-static/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'front-end-static/css/style.min.css' %}">
{% endblock style %}


{% block title %}
Update Activity|Page
{% endblock title %}



{% block content %}
{% include 'parts/navbar.html' %}
<div class="row m-0">
    {% include 'parts/side_nav.html' %}
    <div class="col-9 employees_content mt-4 offset_left" id="side_content">
        <h3 class="text-capitalize my-2">Add Activity</h3>
        <form action="" method="post" class="mt-3">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Activity Title</label>
                <input type="text" class="form-control" name="ActivityName" id="exampleFormControlInput1"
                    value="{{selected_activity.ActivityName}}" placeholder="Activity name">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control" name="Description" placeholder="Activity Description"
                    id="exampleFormControlTextarea1" rows="3">{{selected_activity.Description}}</textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Related Project</label>
                <input type="text" class="form-control" name="Project" id="exampleFormControlInput1"
                    placeholder="the Related Project" value="{{selected_activity.Project}}">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Date and Time</label>
                <input type="datetime-local" class="form-control" value="{{selected_activity.DoneDate}}" name="DoneDate"
                    id="exampleFormControlInput1">
            </div>

            <button type="submit" class="btn btn-info text-white mt-3">
                <span>
                    update
                </span>
            </button>
        </form>


    </div>
</div>


<!-- JAVASCRIPT LOGIC @@@@@@@ -->

{% endblock content %}